add missing CITI refresher course
kumc-bmi/heron-admin pull request #62
Opened 2021-09-03 10:53 UTC by anuforok

2021-09-03 21:16 UTC, nihr43 commented
which of these pull requests is relevant?  is this done?

2021-09-03 21:46 UTC, anuforok commented
> which of these pull requests is relevant? is this done?

@nihr43 this is the one. Thanks

2021-09-07 20:57 UTC, nihr43 requested changes

2021-09-07 20:57 UTC, nihr43 commented on heron_wsgi/traincheck/traincheck.py
> +    WHERE "CRS"."strGroup" IN (:strGroup_1, :strGroup_2, :strGroup_3, :strGroup_4, :strGroup_5, :strGroup_6, :strGroup_7, :strGroup_8)
i spot checked some of the added course names; it looks like none of them exist in the CRS table.  for example:

```
mysql> select count(*) from CRS where strGroup = 'CITI Human Subjects Research';
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

so.. i don't see how these changes are going to fix the problem.

2021-09-14 19:20 UTC, closed without merging